modLoader="javafml"
loaderVersion="[36]"
[[mods]]
modId="litlaunch"
version="0.0.4.2"
displayName="Litlaunch"
authors="Codetoil"
description='''
An api to allow you to use the same mod with many different modloaders(e.g. Forge or Fabric(soon)).
 This also allows for different versions of the modloaders. (i.e. the same mod on 1.7.10 and 1.16.5)
'''
[[dependencies.litlaunch]]
modId="forge"
mandatory=true
versionRange="[36]"
ordering="NONE"
side="BOTH"
[[dependencies.litlaunch]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
