modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
displayURL="https://github.com/Codetoil/LitLaunch-Source" #optional
authors="Codetoil" #optional
[[mods]] #mandatory
modId="litlaunch" #mandatory
version="0.0.3.15" #mandatory
displayName="Lit Launch" #mandatory
description='''
An api to allow you to use the same mod with many different modloaders(e.g. Forge or Fabric).
This also allows for different versions of the modloaders. (i.e. the same mod on 1.7.10 and 1.15.2)
'''